# Generated by Django 2.2.2 on 2019-06-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=3)),
                ('sex', models.BooleanField(choices=[(1, '男'), (0, '女')])),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_app.Class_app')),
            ],
        ),
    ]
